apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webui.fullname" . }}
  labels:
    {{- include "webui.labels" . | nindent 4 }}
    {{- with .Values.deployment.labels }}
    {{ tpl (toYaml .) $ | trim | indent 4 }}
    {{- end }}
  {{- with .Values.deployment.annotations }}
  annotations: {{- tpl (toYaml .) $ | trim | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  {{- with .Values.deployment.strategy }}
  strategy: {{- tpl (toYaml .) $ | trim | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "webui.labels.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "webui.labels" . | nindent 8 }}
        {{- with .Values.pod.labels }}
        {{ tpl (toYaml .) $ | trim | indent 8 }}
        {{- end }}
      {{- with .Values.pod.annotations }}
      annotations: {{- tpl (toYaml .) $ | trim | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{- with .Values.image.pullPolicy }}
        imagePullPolicy: {{ . }}
        {{- end }}
        args:
        {{- with .Values.config.namespace }}
        - -namespace
        - {{ . }}
        {{- end }}
        {{- with .Values.config.resyncInterval }}
        - -resync-interval
        - {{ . }}
        {{- end }}
        {{- with .Values.config.keeperEndpoint }}
        - -keeper-endpoint
        - {{ . }}
        {{- end }}
        {{- with .Values.config.keeperSyncInterval }}
        - -keeper-sync-interval
        - {{ . }}
        {{- end }}
        {{- with .Values.config.eventTraceURLTemplate }}
        - -event-trace-url-template
        - {{ . }}
        {{- end }}
        {{- with .Values.config.logLevel }}
        - -log-level
        - {{ . }}
        {{- end }}
        - -store-data-path
        - "/data"
        - -store-max-events
        - {{ .Values.config.store.gc.maxEventsToKeep | quote }}
        - -store-events-max-age
        - {{ .Values.config.store.gc.eventsMaxAge | quote }}
        env:
        - name: XDG_CONFIG_HOME
          value: /home/jenkins
        - name: LIGHTHOUSE_HMAC_KEY
          valueFrom:
            secretKeyRef: {{- .Values.secrets.lighthouse.hmac.secretKeyRef | toYaml | nindent 14 }}
              optional: true
        {{- range $pkey, $pval := .Values.pod.env }}
        - name: {{ $pkey }}
          value: {{ quote $pval }}
        {{- end }}
        {{- with .Values.pod.envFrom }}
        envFrom:
          {{- toYaml . | trim | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: "/data"
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        {{- with .Values.pod.resources }}
        resources: {{- toYaml . | trim | nindent 10 }}
        {{- end }}
      volumes:
      - name: data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "webui.fullname" . }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- with .Values.pod.securityContext }}
      securityContext: {{- toYaml . | trim | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "webui.fullname" . }}
      enableServiceLinks: {{ .Values.pod.enableServiceLinks }}
      {{- with .Values.pod.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ . }}
      {{- end }}
      {{- with .Values.pod.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.pod.affinity }}
      affinity: {{- tpl (toYaml .) $ | trim | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.nodeSelector }}
      nodeSelector: {{- tpl (toYaml .) $ | trim | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.tolerations }}
      tolerations: {{- tpl (toYaml .) $ | trim | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.hostAliases }}
      hostAliases: {{- tpl (toYaml .) $ | trim | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.schedulerName }}
      schedulerName: {{ tpl . $ | trim }}
      {{- end }}
